name: clang-format
on:
  push:
    branches: main
  pull_request:
    branches: main


jobs:
  style:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: "*"
            exclude: "lib/**"

    steps:
      - uses: actions/checkout@v3
      - name: 🎨 Run clang-format style check
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: "15"
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
          fallback-style: "Google"